language: c
sudo: false
services:
  - docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
  - wget https://raw.githubusercontent.com/simonjbeaumont/ocaml-travis-coveralls/master/travis-coveralls.sh
script: bash ./.travis-docker.sh && bash ./travis-coveralls.sh
env:
 global:
   - PACKAGE="osilo"
   - INSTALL=true
   - TESTS=true
   - PINS="macaroons:https\://github.com/nojb/ocaml-macaroons.git lwt:2.6.0"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03.0
