language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="osilo"
   - INSTALL=true
   - TESTS=true
   - PINS="macaroons:https\://github.com/nojb/ocaml-macaroons.git lwt:2.6.0"
   - EXTRA_REMOTES="https://github.com/janestreet/opam-repository.git"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.04.0
