language: c
sudo: false
services:
  - docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="osilo"
   - INSTALL=true
   - TESTS=true
   - PINS="macaroons:https\://github.com/nojb/ocaml-macaroons.git lwt:2.6.0"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03.0
