language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="osilo"
   - INSTALL=false
   - TESTS=true
   - PINS="macaroons:https\://github.com/m-harrison/ocaml-macaroons#macaroons-target"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03.0
