language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
 global:
   - PACKAGE="osilo"
   - DEPOPTS="async cohttp core nocrypto threads webmachine yojson"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="opam depext -ui github cowabloga opium slacko"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.03.0
